### ISSUE TITLE
use metalsmith-markdownit with markdown-it plugins

### ISSUE THREAD

**Issue by oupala** [mayo/metalsmith-markdownit#15]
As asked by @bishless, it could be useful to be able to user metalsmith-markdownit with markdown-it plugins.

I can see that you proposed a workaround in #1, but do you plan to add a real option to use plugins?

It could be great!

At least, a full example would be welcome!

**Comment by mayo** [comment]
The example in #1 is not a workaround, but intended use. There is no reason why metalsmith-markdownit should abstract markdown-it, which already has a well built and documented API. I'm not sure what you mean by "real option"? Getting the actual markdownit parser is about as real as you can get.

There is an example in the readme already:

> If you need access to markdown-it directly to enable features or use plugins, you can access the parser directly:

```node
var markdown = require('metalsmith-markdownit');

var md = markdown('zero', { html: true });
md.parser.enable(['emphasis', 'html_block', 'html_tag']);

metalsmith.use(md);
```

**Comment by oupala** [comment]
Ok, thanks for your anwser.

I was thinking about an embedded config as it is implemented in hexo:

```yaml
# Markdown-it config
## Docs: https://github.com/celsomiranda/hexo-renderer-markdown-it/wiki
markdown:
  render:
    html: true
    xhtmlOut: false
    breaks: false
    linkify: true
    typographer: true
    quotes: '“”‘’'
  plugins:
    - markdown-it-abbr
    - markdown-it-footnote
```

Could you please write an example that uses [markdown-it-deflist](https://github.com/markdown-it/markdown-it-deflist)?

I can't get it to work without errors:

> TypeError: "callback" argument must be a function

Here is my current non-working code:

```js
var markdown = markdownit('zero', { html: true });
markdown.parser.enable(['emphasis', 'html_block']);
markdown.parser.enable(require('markdown-it-deflist'));
```
